//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eurosim.Graphics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eurosim.Graphics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] arrowblue {
            get {
                object obj = ResourceManager.GetObject("arrowblue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] arrowred {
            get {
                object obj = ResourceManager.GetObject("arrowred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blackcd {
            get {
                object obj = ResourceManager.GetObject("blackcd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bottleblue {
            get {
                object obj = ResourceManager.GetObject("bottleblue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bottlered {
            get {
                object obj = ResourceManager.GetObject("bottlered", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] camera {
            get {
                object obj = ResourceManager.GetObject("camera", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cd {
            get {
                object obj = ResourceManager.GetObject("cd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] chest {
            get {
                object obj = ResourceManager.GetObject("chest", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] clothblue {
            get {
                object obj = ResourceManager.GetObject("clothblue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] clothred {
            get {
                object obj = ResourceManager.GetObject("clothred", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] coinactuatorbody {
            get {
                object obj = ResourceManager.GetObject("coinactuatorbody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ingot {
            get {
                object obj = ResourceManager.GetObject("ingot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap king {
            get {
                object obj = ResourceManager.GetObject("king", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] king1 {
            get {
                object obj = ResourceManager.GetObject("king1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kingtower2 {
            get {
                object obj = ResourceManager.GetObject("kingtower2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kingtower3 {
            get {
                object obj = ResourceManager.GetObject("kingtower3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] palm {
            get {
                object obj = ResourceManager.GetObject("palm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap queen {
            get {
                object obj = ResourceManager.GetObject("queen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] queen1 {
            get {
                object obj = ResourceManager.GetObject("queen1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] queentower2 {
            get {
                object obj = ResourceManager.GetObject("queentower2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] queentower3 {
            get {
                object obj = ResourceManager.GetObject("queentower3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] table {
            get {
                object obj = ResourceManager.GetObject("table", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] table1 {
            get {
                object obj = ResourceManager.GetObject("table1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] totem {
            get {
                object obj = ResourceManager.GetObject("totem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap untitled {
            get {
                object obj = ResourceManager.GetObject("untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
